### ISSUE TITLE
可否自定义证书

### ISSUE THREAD

**Issue by dzluck** [crazypeace/naive#11]
感谢大佬的项目，关注您很久了，通过您的博客学习了很多，这次请教下，这个项目可否自定义证书呢？勇哥的脚本可以自定义证书，但没开源，脚本混淆了。

**Comment by crazypeace** [comment]
1. 关于解密 
```
wget -N https://gitlab.com/rwkgyg/naiveproxy-yg/raw/main/naiveproxy.sh
bash <(curl -L https://gitlab.com/crazypeace/tuic-yg-unpack/-/raw/main/unpack.sh) naiveproxy.sh
```
原理解释 https://zelikk.blogspot.com/2023/07/tui-yg-unpack.html

2. 关于naiveproxy自定义证书.
用法和Caddy自定义证书一样. 添加 tls 字段就是了.
你在yg的脚本里面可以看到，就是这样实现的
![image](https://github.com/user-attachments/assets/fb50e2cc-3698-4e53-8dce-4749bae95b5f)

3. 如果你想自签证书
https://github.com/crazypeace/hy2#%E6%89%8B%E6%90%93%E6%AD%A5%E9%AA%A4%E5%A6%82%E4%B8%8B
![image](https://github.com/user-attachments/assets/bebe6c92-ac31-416d-b132-d912562cc496)

**Comment by dzluck** [comment]
感谢大佬的回复并提供思路，我去研究下，祝生活愉快！

**Comment by crazypeace** [comment]
不客气 :) 祝你成功!
